/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AuditTrail: typeof import('./src/components/audit/AuditTrail.vue')['default']
    CardStatisticsHorizontal: typeof import('./src/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./src/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./src/@core/components/cards/CardStatisticsWithImages.vue')['default']
    DeleteBtn: typeof import('./src/components/btns/deleteBtn.vue')['default']
    DocumentPreviewModal: typeof import('./src/components/DocumentPreviewModal.vue')['default']
    ErrorHeader: typeof import('./src/components/ErrorHeader.vue')['default']
    MoreBtn: typeof import('./src/@core/components/MoreBtn.vue')['default']
    NotificationModal: typeof import('./src/components/forms/NotificationModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectCustom: typeof import('./src/components/forms/selectCustom.vue')['default']
    SelectCustomWithFilter: typeof import('./src/components/forms/selectCustomWithFilter.vue')['default']
    SelectCustomWithFilter2: typeof import('./src/components/forms/selectCustomWithFilter2.vue')['default']
    ShareDialog: typeof import('./src/components/ShareDialog.vue')['default']
    SubmitBtn: typeof import('./src/components/btns/SubmitBtn.vue')['default']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
    UpgradeToPro: typeof import('./src/components/UpgradeToPro.vue')['default']
  }
}
